-- 01_create_tables_cn3.sql
-- Tao cac bang cho site Chi nhanh 3.
-- Chay bang user/schema du lieu cua CN3, vi du: giamdoc_cn3.

SET DEFINE OFF;

CREATE TABLE CHINHANH (
    MaCN VARCHAR2(15) PRIMARY KEY,
    TenCN VARCHAR2(100),
    DiaChi VARCHAR2(250)
);

CREATE TABLE SACH (
    MaSach VARCHAR2(15) PRIMARY KEY,
    TenSach VARCHAR2(500),
    TacGia VARCHAR2(300),
    TheLoai VARCHAR2(50),
    NhaXuatBan VARCHAR2(300),
    GiaBan NUMBER(12, 2)
);

CREATE TABLE KHACHHANG (
    MaKH VARCHAR2(15) PRIMARY KEY,
    HoTen VARCHAR2(100),
    GioiTinh VARCHAR2(10),
    NgaySinh DATE,
    DiaChi VARCHAR2(250),
    SoDienThoai VARCHAR2(15)
);

CREATE TABLE NHANVIEN (
    MaNV VARCHAR2(15) PRIMARY KEY,
    HoTen VARCHAR2(100),
    GioiTinh VARCHAR2(10),
    NgaySinh DATE,
    SoDienThoai VARCHAR2(15),
    NgayVaoLam DATE,
    MaCN VARCHAR2(15) REFERENCES CHINHANH(MaCN)
);

CREATE TABLE KHO_NHAP (
    MaCN VARCHAR2(15),
    MaSach VARCHAR2(15),
    NgayNhap DATE,
    SoLuongNhap NUMBER,
    GiaNhap NUMBER(12, 2),
    PRIMARY KEY (MaCN, MaSach, NgayNhap),
    FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN),
    FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
);

CREATE TABLE KHO_BAN (
    MaCN VARCHAR2(15),
    MaSach VARCHAR2(15),
    SoLuongTon NUMBER DEFAULT 0,
    TrangThai VARCHAR2(20),
    PRIMARY KEY (MaCN, MaSach),
    FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN),
    FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
);

CREATE TABLE HOADON (
    MaHD VARCHAR2(20) PRIMARY KEY,
    MaKH VARCHAR2(15) REFERENCES KHACHHANG(MaKH),
    MaNV VARCHAR2(15) REFERENCES NHANVIEN(MaNV),
    NgayLap TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TongTien NUMBER(15, 2)
);

CREATE TABLE CHITIET_HD (
    MaHD VARCHAR2(20),
    MaSach VARCHAR2(15),
    SoLuong NUMBER,
    PRIMARY KEY (MaHD, MaSach),
    FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
    FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
);

