version: '3.8'

services:
  mongodb-standalone-1:
    image: mongo:latest
    container_name: mongodb-may1
    # Máy 1 sẽ làm Node Độc lập chứa dữ liệu CN001
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_1:/data/db
    restart: always

volumes:
  mongo_data_1:
