version: '3.8'

services:
  mongodb-standalone-2:
    image: mongo:latest
    container_name: mongodb-may2
    # Máy 2 sẽ làm Node Độc lập chứa dữ liệu CN002
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_2:/data/db
    restart: always

volumes:
  mongo_data_2:
